source:
  type: excel
  path: ${ACR_HIST_ORIGIN}
  sub_paths: 
    month: ['Activos','Inactivos']
    hist: ['Activos/Historico', 'Inactivos/Historico']

target:
  schema: GRC
  table: GCC_HIST_ACR
  mode: append