CREATE TABLE "GRC"."GCC_HIST_ALTERNATIVAS" (
    "PERIODO" NUMBER (6,0) NOT NULL,
    "GCC_TIPO_ALFABETICO" CHAR(3 BYTE) NOT NULL, 
    "ASO_IDENTIFICACION" NUMBER(17,0) NOT NULL, 
    "FECHA_APLICACION" DATE NOT NULL, 
    "APLICADO_APORTES" NUMBER(15,0), 
    "APLICADO_CALAMIDAD" NUMBER(15,0), 
    "APLICADO_RECREACION" NUMBER(15,0),
    "TOTAL_PAGADO_COOMEVA" NUMBER(15,0),
    "PROCESO_ORIGEN" CHAR(20 BYTE),
    "ALTERNATIVA" CHAR(50 BYTE), 
    "FECHA_INSERCION" TIMESTAMP (6),
    "INDICADOR_CRUZE_INAC_ACT" NUMBER(1,0) NOT NULL,
    CONSTRAINT "GCC_HIST_ALTERNATIVAS_PK" PRIMARY KEY ("PERIODO","GCC_TIPO_ALFABETICO","ASO_IDENTIFICACION","FECHA_APLICACION","ALTERNATIVA")
    USING INDEX TABLESPACE "GRC_I_04" ENABLE,
    CONSTRAINT "GCC_HIST_ALTERNATIVAS_FK01" FOREIGN KEY ("ASO_IDENTIFICACION", "GCC_TIPO_ALFABETICO") 
    REFERENCES "GRC"."GCC_ASOCIADO" ("ASO_IDENTIFICACION", "GCC_TIPO_ALFABETICO") ENABLE
)
TABLESPACE "GRC_D_04";

CREATE INDEX "GRC"."GCC_HIST_ALTERNATIVAS_IDX01" 
ON "GRC"."GCC_HIST_ALTERNATIVAS" ("ASO_IDENTIFICACION", "PERIODO")
TABLESPACE "GRC_I_04";